# run with:
#   F="XXX.go" air

root = "."

[build]
cmd = "go build -o ./tmp/main ./$F"

# run tests
#full_bin = "go test -v --bench ./$F --benchmem"
#exclude_regex = []
#cmd = "echo"

#full_bin = "dlv exec ./tmp/main --"
stop_on_error = true
delay = 200
